name: CI
on:
  # События, которые запускают
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
# jobs запускаются параллельно, если не указана последовательность 
jobs:
  #  Название job вы можете назвать как угодно
  my_build_job:
    # Операционная система в виртуальной машине, в которой запускаются процессы
    runs-on: ubuntu-latest
    steps:
      # Action от github: проверяет репозиторий, гит и т.д.
      - uses: actions/checkout@v3
      # Устанавливаем все необходимые зависимости и запускаем тесты node
      - name: npm install, test and build
        run: |
          npm install
          npm run build
